// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsa2V9meCrxX7M-hCxA6rE6wFfc5njn3o',
    appId: '1:813215857306:web:21138ae487fddd3a26fd23',
    messagingSenderId: '813215857306',
    projectId: 'emergency-app-84ab0',
    authDomain: 'emergency-app-84ab0.firebaseapp.com',
    storageBucket: 'emergency-app-84ab0.firebasestorage.app',
    measurementId: 'G-E3MH0LGZQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGvvB-gGioX0ZONoIA0f4wrTyd43K8RV4',
    appId: '1:813215857306:android:a4306a96e3f2938a26fd23',
    messagingSenderId: '813215857306',
    projectId: 'emergency-app-84ab0',
    storageBucket: 'emergency-app-84ab0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsa2V9meCrxX7M-hCxA6rE6wFfc5njn3o',
    appId: '1:813215857306:web:64eee1fae2d1093626fd23',
    messagingSenderId: '813215857306',
    projectId: 'emergency-app-84ab0',
    authDomain: 'emergency-app-84ab0.firebaseapp.com',
    storageBucket: 'emergency-app-84ab0.firebasestorage.app',
    measurementId: 'G-H9MJP489SD',
  );

}